using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using Cosmechic.Models;
using Cosmechic.Tests.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Cosmechic.Tests
{
    // COSMECHIC-CATALOG-001 (section 54) : SKU/slug, validation produit, relations image,
    // suppression sûre, autorisation admin marque.
    public class CatalogAdminTests : IDisposable
    {
        private readonly CustomWebApplicationFactory _factory = new();

        public CatalogAdminTests()
        {
            TestDataSeeder.SeedStandardFixture(_factory);
        }

        private static readonly byte[] JpegBytes = { 0xFF, 0xD8, 0xFF, 0xE0, 0, 0, 0, 0, 0, 0 };

        // COSMECHIC-CATALOG-001 : Produit.Image est un type référence non-nullable —
        // ASP.NET Core valide implicitement sa présence même sans [Required] explicite.
        // Un vrai formulaire Create/Edit envoie toujours un fichier ; on reproduit donc un
        // vrai envoi multipart plutôt qu'un simple formulaire encodé.
        private static MultipartFormDataContent ProduitForm(string nom, string categorieId, string sku = "", string slug = "")
        {
            var content = new MultipartFormDataContent
            {
                { new StringContent(nom), "Nom" },
                { new StringContent(categorieId), "CategorieId" },
                { new StringContent("desc"), "Description" },
                { new StringContent("9.99"), "Prix" },
                { new StringContent("3"), "Stock" },
                { new StringContent("true"), "Disponible" },
                { new StringContent(sku), "Sku" },
                { new StringContent(slug), "Slug" },
                // Produit.Image (string, type référence non-nullable) est validé
                // implicitement par ASP.NET Core indépendamment du fichier IFormFile ci-
                // dessous (espaces de liaison distincts) — écrasé par le vrai nom stocké
                // dès qu'un fichier est effectivement présent (voir Create/Edit POST).
                { new StringContent("placeholder.jpg"), "Image" },
            };
            var fileContent = new ByteArrayContent(JpegBytes);
            fileContent.Headers.ContentType = new MediaTypeHeaderValue("image/jpeg");
            content.Add(fileContent, "Image", "produit.jpg");
            return content;
        }

        [Fact]
        public async Task Create_MissingSku_IsRejectedWithoutCreatingProduct()
        {
            var client = _factory.CreateTestClient().AsAdmin();
            var before = _factory.Query(c => c.Produits.Count());

            var response = await client.PostAsync("/Produits/Create", ProduitForm("Nouveau Produit", TestDataSeeder.CategoryId.ToString()));

            Assert.Equal(HttpStatusCode.OK, response.StatusCode); // redisplays the form, not a redirect
            var after = _factory.Query(c => c.Produits.Count());
            Assert.Equal(before, after);
        }

        [Fact]
        public async Task Create_DuplicateSku_IsRejected()
        {
            _factory.Seed(context =>
            {
                context.Produits.Add(new Produit
                {
                    Nom = "Existant",
                    CategorieId = TestDataSeeder.CategoryId,
                    Prix = 1,
                    Stock = 1,
                    Disponible = true,
                    Image = "x.jpg",
                    Sku = "DUP-001",
                    RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 9 },
                });
            });

            var client = _factory.CreateTestClient().AsAdmin();
            var response = await client.PostAsync("/Produits/Create", ProduitForm("Un Autre", TestDataSeeder.CategoryId.ToString(), sku: "DUP-001"));

            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            var count = _factory.Query(c => c.Produits.Count(p => p.Sku == "DUP-001"));
            Assert.Equal(1, count);
        }

        [Fact]
        public async Task Create_EmptySlug_IsAutoGeneratedFromName()
        {
            var client = _factory.CreateTestClient().AsAdmin();

            var response = await client.PostAsync("/Produits/Create", ProduitForm("Savon Doux À l'Avoine", TestDataSeeder.CategoryId.ToString(), sku: "AUTO-SLUG-1"));

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            var produit = _factory.Query(c => c.Produits.FirstOrDefault(p => p.Sku == "AUTO-SLUG-1"));
            Assert.NotNull(produit);
            Assert.Equal("savon-doux-a-lavoine", produit!.Slug);
        }

        [Fact]
        public async Task Edit_DoesNotResetDateCreation()
        {
            var originalDate = _factory.Query(c => c.Produits.First(p => p.ProduitId == TestDataSeeder.ProduitId).DateCreation);

            var client = _factory.CreateTestClient().AsAdmin();
            var form = ProduitForm("Creme hydratante modifiee", TestDataSeeder.CategoryId.ToString(), sku: "COS-EDIT-1");
            form.Add(new StringContent(TestDataSeeder.ProduitId.ToString()), "ProduitId");
            var response = await client.PostAsync($"/Produits/Edit/{TestDataSeeder.ProduitId}", form);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            var updatedDate = _factory.Query(c => c.Produits.First(p => p.ProduitId == TestDataSeeder.ProduitId).DateCreation);
            Assert.Equal(originalDate, updatedDate);
        }

        [Fact]
        public async Task DeleteProduct_WithOrderHistory_DeactivatesInsteadOfDeleting()
        {
            // TestDataSeeder.ProduitId a déjà un OrderDetail associé.
            var client = _factory.CreateTestClient().AsAdmin();

            var response = await client.PostAsync($"/Produits/Delete/{TestDataSeeder.ProduitId}", content: null);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            var produit = _factory.Query(c => c.Produits.FirstOrDefault(p => p.ProduitId == TestDataSeeder.ProduitId));
            Assert.NotNull(produit);
            Assert.False(produit!.Disponible);
        }

        [Fact]
        public async Task DeleteProduct_WithoutHistory_IsHardDeleted()
        {
            var newId = _factory.Query(c =>
            {
                var p = new Produit
                {
                    Nom = "Sans historique",
                    CategorieId = TestDataSeeder.CategoryId,
                    Prix = 1,
                    Stock = 1,
                    Disponible = true,
                    Image = "x.jpg",
                    Sku = "NOHIST-1",
                    RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 8 },
                };
                c.Produits.Add(p);
                c.SaveChanges();
                return p.ProduitId;
            });

            var client = _factory.CreateTestClient().AsAdmin();
            var response = await client.PostAsync($"/Produits/Delete/{newId}", content: null);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            var stillExists = _factory.Query(c => c.Produits.Any(p => p.ProduitId == newId));
            Assert.False(stillExists);
        }

        [Fact]
        public async Task DeleteCategory_WithProducts_IsBlocked()
        {
            var client = _factory.CreateTestClient().AsAdmin();

            var response = await client.PostAsync($"/Categories/Delete/{TestDataSeeder.CategoryId}", content: null);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            var stillExists = _factory.Query(c => c.Categories.Any(cat => cat.CategorieId == TestDataSeeder.CategoryId));
            Assert.True(stillExists);
        }

        [Fact]
        public async Task Brands_NonAdmin_IsDenied()
        {
            var client = _factory.CreateTestClient().AsCustomerA();

            var response = await client.GetAsync("/Brands/Index");

            Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
        }

        [Fact]
        public async Task Brands_Admin_CanCreateBrand()
        {
            var client = _factory.CreateTestClient().AsAdmin();
            var form = new FormUrlEncodedContent(new Dictionary<string, string> { ["Nom"] = "Marque Test Unique" });

            var response = await client.PostAsync("/Brands/Create", form);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            var brand = _factory.Query(c => c.Brands.FirstOrDefault(b => b.Nom == "Marque Test Unique"));
            Assert.NotNull(brand);
            Assert.Equal("marque-test-unique", brand!.Slug);
            Assert.True(brand.Disponible);
        }

        [Fact]
        public async Task AddImage_FirstUpload_BecomesPrimaryAutomatically()
        {
            var client = _factory.CreateTestClient().AsAdmin();

            using var content = new MultipartFormDataContent();
            var jpegBytes = new byte[] { 0xFF, 0xD8, 0xFF, 0xE0, 0, 0, 0, 0, 0, 0 };
            var fileContent = new ByteArrayContent(jpegBytes);
            fileContent.Headers.ContentType = new MediaTypeHeaderValue("image/jpeg");
            content.Add(fileContent, "file", "gallery.jpg");

            var response = await client.PostAsync($"/Produits/AddImage/{TestDataSeeder.ProduitId}", content);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            var image = _factory.Query(c => c.ProduitImages.FirstOrDefault(pi => pi.ProduitId == TestDataSeeder.ProduitId));
            Assert.NotNull(image);
            Assert.True(image!.IsPrimary);
        }

        [Fact]
        public async Task SetPrimaryImage_EnforcesSingleInvariant()
        {
            var (image1Id, image2Id) = _factory.Query(c =>
            {
                var img1 = new ProduitImage { ProduitId = TestDataSeeder.ProduitId, FileName = "a.jpg", IsPrimary = true, SortOrder = 0 };
                var img2 = new ProduitImage { ProduitId = TestDataSeeder.ProduitId, FileName = "b.jpg", IsPrimary = false, SortOrder = 1 };
                c.ProduitImages.Add(img1);
                c.ProduitImages.Add(img2);
                c.SaveChanges();
                return (img1.ProduitImageId, img2.ProduitImageId);
            });

            var client = _factory.CreateTestClient().AsAdmin();
            var form = new FormUrlEncodedContent(new Dictionary<string, string> { ["imageId"] = image2Id.ToString() });
            var response = await client.PostAsync($"/Produits/SetPrimaryImage/{TestDataSeeder.ProduitId}", form);

            Assert.Equal(HttpStatusCode.Redirect, response.StatusCode);
            var images = _factory.Query(c => c.ProduitImages.Where(pi => pi.ProduitId == TestDataSeeder.ProduitId).ToList());
            Assert.Single(images, i => i.IsPrimary);
            Assert.True(images.First(i => i.ProduitImageId == image2Id).IsPrimary);
            Assert.False(images.First(i => i.ProduitImageId == image1Id).IsPrimary);
        }

        public void Dispose() => _factory.Dispose();
    }
}
